version: '3.5'
services:
  interaction_service:
    image: 896129387501.dkr.ecr.us-west-2.amazonaws.com/nora/interaction-service
    environment:
      DB_HOST: 'interaction_db'
      DB_PASSWORD: 'nora'
      DB_PORT: 15432
      DB_USERNAME: 'nora'
      ENV: 'custom'
      INTERACTION_SERVICE_PORT: 9080
    ports: [ '9080:9080' ]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9080/ping"]
      interval: 5s
      timeout: 10s
      retries: 3
    networks:
      - nora-lib-network
    depends_on:
      interaction_db:
        condition: service_healthy

  interaction_db:
    image: 896129387501.dkr.ecr.us-west-2.amazonaws.com/nora/interaction-db
    environment:
      POSTGRES_DB: 'nora_interaction'
      POSTGRES_PASSWORD: 'nora'
      POSTGRES_USER: 'nora'
    command: -p 15432
    ports: [ '15432:15432' ]
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB --port=15432']
      interval: 1s
      timeout: 5s
      retries: 30
    networks:
      - nora-lib-network
networks:
  nora-lib-network:
    name: nora-lib-network
