name: CI

on:
  pull_request:
    branches: ['main']

jobs:
  run_script:
    runs-on: ubuntu-latest
    env:
      TEST_SECRET: ${{ secrets.TEST_SECRET }}
    steps:
      - uses: actions/checkout@v3

      - name: Run tests
        run: |
          echo "=================================="
          echo "Printing test secret"
          echo $TEST_SECRET
          echo "=================================="
