name: CI

on:
  pull_request:
    branches: ['main']

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run tests
        run: |
          echo "Running verify.sh"
          ./verify.sh
          if [ $? -ne 0 ]; then
            echo "Error: Verify step failed"
            exit 1
          fi
